" シンタックス・ハイライトを有効化
syntax on
" クリップボードを有効化
set clipboard=unnamedplus
" 行番号を表示
set number
" 文字コード指定（vimで文字化けを防止する）
set encoding=utf-8
" ファイルエンコード指定
set fileencodings=utf-8,iso-2022-jp,euc-jp,sjis
" 自動認識させる改行コードの指定
set fileformats=unix,dos,mac
" 検索結果に該当するものを全てハイライト
set hlsearch
" 検索結果で大文字小文字を区別しない
set ignorecase
" 入力途中でも打ち込んだところまでで検索する
set incsearch
" 意図的に大文字が入力された場合は、大文字小文字を区別するようにする
set smartcase
" 最下ウィンドウにステータスを常に表示する
set laststatus=2
" 改行時、自動でちょうどよいインデントに
set autoindent
" 現在行・現在文字位置を表示する
set ruler
